name: Stephen Brennan
author: Stephen Brennan
title: Talks by Stephen Brennan
description: Talks by Stephen Brennan
keywords: cs programming student talks
logo: /images/me.jpg

url: http://brennan.io/talks
baseurl: /talks
root: http://brennan.io

paginate: 5
paginate_path: "page:num"

markdown: redcarpet
highlighter: pygments
permalink: pretty

exclude: ["README.md"]

startslide: "<section data-markdown><script type='text/template'>"
nextslide: "</script></section><section data-markdown><script type='text/template'>"
endslide: "</script></section>"

startvertical: "<section>"
endvertical: "</section>"

nextvertical: "</script></section></section><section><section data-markdown><script type='text/template'>"
