name: "Stephen Brennan"
url: "http://stephen-brennan.com/talks"
baseurl: "/talks"

paginate: 5
paginate_path: "page:num"

markdown: redcarpet
highlighter: pygments
permalink: pretty

exclude: ["README.md"]

startslide: "<section data-markdown><script type='text/template'>"
nextslide: "</script></section><section data-markdown><script type='text/template'>"
endslide: "</script></section>"

startvertical: "<section>"
endvertical: "</section>"